### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by chouenyu0808**
Fixed the problem that docker was not rebuilt when the api service changed IP.

### CODE REVIEW

**Comment by chouenyu0808** [comment]
Fixed the problem that docker was not rebuilt when the api service changed IP.

**Comment by chouenyu0808** [comment]
Fixed the problem that docker was not rebuilt when the api service changed IP.

**Comment by rien** [comment]
Hi @chouenyu0808, there is already a similar fix on master that adds this feature to the dolos-web Dockerfile: https://github.com/dodona-edu/dolos/blob/main/web/Dockerfile#L20

This is currently not released however, so you need to build the dolos-web docker yourself currently.

**Comment by chouenyu0808** [comment]
Can you tell me the steps to use it? Because I still can't use it

Rien ***@***.***> 於 2024年9月26日 週四 下午3:42寫道：

**Pull request closed without merging**
